name: test

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: /
        python -m pip install --upgrade pip
        if [ -f leetcode-contests/requirements.txt ]; then pip install -r leetcode-contests/requirements.txt; fi
    - name: Test
      run: /
        python test.py
        
    
      
