name: test

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "leetcode-contests/requirements.txt"
    - name: Test
      run: /
        python leetcode-contests/test.py
        
    
      
